Fitnesspro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('',include('users.urls'),name='users'),
    path('adminfitness/',include('adminfitness.urls'),name='adminfitness'),
    path('trainer/',include('trainer.urls'),name='trainer'),
    path('client/',include('client.urls'),name='client'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views


urlpatterns = [
    path('login/', views.login),

    path('login_post/',views.login_post),
    path('admin_addtrainers_post/', views.admin_addtrainers_post),
    path('admin_viewtrainers_post/', views.admin_viewtrainers_post),
    path('admin_deletetrainer/<id>', views.admin_deletetrainer),
    path('admin_updatetrainers_post/', views.admin_updatetrainers_post),

    path('forget_password/', views.forget_password),
    path('forget_password_post/', views.forget_password_post),
    # path('admin_viewuser/', views.admin_viewuser),
    path('admin_viewuser_post/', views.admin_viewuser_post),
    # path('admin_viewusermoredetails_post/', views.admin_viewusermoredetails_post),
    path('admin_addcategory_post/', views.admin_addcategory_post),
    path('admin_editcategory_post/', views.admin_editcategory_post),
    path('admin_viewcategory_post/', views.admin_viewcategory_post),
    path('admin_deletecategory/<id>', views.admin_deletecategory),
    path('admin_viewusercomplaint_post/', views.admin_viewusercomplaint_post),
    path('admin_usercomplaintreply_post/', views.admin_usercomplaintreply_post),
    path('admin_viewfeedback_post/', views.admin_viewfeedback_post),
    path('admin_viewposturevideo_post/', views.admin_viewposturevideo_post),
    path('admin_viewpayment_post/', views.admin_viewpayment_post),
    path('admin_changepwd_post/', views.admin_changepwd_post),

    path('trainer_addposture_post/', views.trainer_addposture_post),
    path('trainer_viewposture_post/', views.trainer_viewposture_post),
    path('trainer_editposture_post/', views.trainer_editposture_post),
    path('trainer_deletetposture/<id>', views.trainer_deletetposture),
    path('trainer_viewuser_post/', views.trainer_viewuser_post),
    path('trainer_adddietplan_post/', views.trainer_adddietplan_post),
    path('trainer_viewdietplan_post/', views.trainer_viewdietplan_post),
    path('trainer_changepwd_post/', views.trainer_changepwd_post),

    path('user_signup_post/', views.user_signup_post),
    path('user_viewposture_post/', views.user_viewposture_post),
    path('user_viewcomplaintreply_post/', views.user_viewcomplaintreply_post),
    path('user_sentfeedback_post/', views.user_sentfeedback_post),
    path('user_payment_post/', views.user_payment_post),
    path('user_viewdietplan_post/', views.user_viewdietplan_post),
    path('user_changepwd_post/', views.user_changepwd_post),
    path('user_sendcomplaint_post/',views.user_sendcomplaint_post),

    path('admin_addtrainers/',views.admin_addtrainers),
    path('admin_viewtrainers/',views.admin_viewtrainers),
    path('admin_updatetrainers/<tid>',views.admin_updatetrainers),
    path('admin_viewuser/',views.admin_viewuser),
    path('admin_viewusermoredetails/<id>',views.admin_viewusermoredetails),
    path('admin_addcategory/',views.admin_addcategory),
    path('admin_viewcategory/',views.admin_viewcategory),
    path('admin_editcategory/<cid>',views.admin_editcategory),
    path('admin_viewusercomplaint/',views.admin_viewusercomplaint),
    path('admin_usercomplaintreply/<id>', views.admin_usercomplaintreply),
    path('admin_viewfeedback/', views.admin_viewfeedback),
    path('admin_viewpayment/', views.admin_viewpayment),
    path('admin_viewposturevideo/<tid>', views.admin_viewposturevideo),
    path('admin_changepwd/', views.admin_changepwd),
    path('admin_logout/', views.admin_logout),
    path('admin_homepage/', views.admin_homepage),


    path('trainer_viewprofile/', views.trainer_viewprofile),
    path('trainer_addposture/', views.trainer_addposture),
    path('trainer_viewposture/', views.trainer_viewposture),
    path('trainer_playvideo/', views.trainer_playvideo),
    path('trainer_editposture/<id>', views.trainer_editposture),
    path('trainer_viewuser/', views.trainer_viewuser),
    path('trainer_viewusermoredetails/<id>', views.trainer_viewusermoredetails),
    path('trainer_adddietplan/', views.trainer_adddietplan),
    path('trainer_viewdietplan/', views.trainer_viewdietplan),
    path('trainer_editdietplan/<id>', views.trainer_editdietplan),
    path('trainer_editdietplan_post/', views.trainer_editdietplan_post),
     path('trainer_deletetdiet/<id>', views.trainer_deletetdiet),
    path('trainer_querychat/', views.trainer_querychat),
    path('trainer_changepwd/', views.trainer_changepwd),
    path('trainer_logout/', views.trainer_logout),
    path('trainer_homepage/', views.trainer_homepage),

    path('user_signup/', views.user_signup),
    path('user_viewprofile/', views.user_viewprofile),
    path('user_viewposture/', views.user_viewposture),
    path('user_playvideo/', views.user_playvideo),
    path('user_sentcomplaint/', views.user_sentcomplaint),
    path('user_viewcomplaintreply/', views.user_viewcomplaintreply),
    path('user_sentfeedback/', views.user_sentfeedback),
    path('user_viewdietplan/', views.user_viewdietplan),
    path('user_sendquery/', views.user_sendquery),
    path('user_payment/', views.user_payment),
    path('user_changepwd/', views.user_changepwd),
    path('user_logout/', views.user_logout),
    path('user_homepage/', views.user_homepage),
    path('user_view_trainer/', views.user_view_trainer),
    path('user_view_trainer_post/', views.user_view_trainer_post),
    path('rating/<id>', views.rating),
    path('rating_post/', views.rating_post),



    path('chat/<toid>', views.chat),
    path('chat_send/<msg>/<tid>', views.chat_send),
    path('chat_view/<tid>', views.chat_view),

    path('chat1/<toid>', views.chat1),
    path('chat_send1/<msg>/<tid>', views.chat_send2),
    path('chat_view1/<tid>', views.chat_view2),

]

users/urls.py
# app_name = 'users'
from django.urls import path
from.views import *
urlpatterns = [
    path('',Login.as_view(),name='login'),
    path('clientregistration/',Clientregistration.as_view(),name='clientregistration'),
    path('logout/',Logout.as_view(),name='logout'),
    path('admin_homepage/',Adminhome.as_view(),name='admin_homepage'),
    path('trainer_homepage/',Trainerhome.as_view(),name='trainer_homepage'),
    path('client_homepage/',Clienthome.as_view(),name='client_homepage'),
    path('userloginapi/', UserLoginapi.as_view(), name='userloginapi'),


    path('user_signup/', Clientregistration.as_view(), name='usersignup'),
    path('forgotpassword/', ForgotPassword.as_view(), name='forgotpassword'),
    path('changepassword/', PasswordChange.as_view(), name='changepassword'),

    path('forgotpasswordapi/', ForgotPasswordAPIView.as_view(), name='forgotpasswordapi'),
    path('changepasswordapi/', PasswordChangeAPIView.as_view(), name='changepasswordapi'),
    path('changeprofilepasswordapi/',ProfilePasswordChange.as_view()),
    path('changeprofileplanapi/', ProfilePlanChange.as_view()),

]

myapp/models.py
from django.db import models

# Create your models here.

class Login(models.Model):
    username=models.CharField(max_length=100)
    password=models.CharField(max_length=100)
    type=models.CharField(max_length=100)

class User(models.Model):
    name=models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    height = models.CharField(max_length=100)
    weight = models.CharField(max_length=100)
    dob = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    photo= models.CharField(max_length=500,default='')
    LOGIN=models.ForeignKey(Login,on_delete=models.CASCADE,default=1)

class Trainer(models.Model):
    name = models.CharField(max_length=100)
    dob = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    certificate = models.CharField(max_length=500)
    photo= models.CharField(max_length=500)
    LOGIN=models.ForeignKey(Login,on_delete=models.CASCADE,default=1)

class Category(models.Model):
    categoryname = models.CharField(max_length=100)


class Posture(models.Model):
    CATEGORY = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    TRAINER = models.ForeignKey(Trainer,on_delete=models.CASCADE,default=1)
    title = models.CharField(max_length=100)
    image = models.CharField(max_length=1000)
    video = models.FileField()

class Chat(models.Model):
    message = models.CharField(max_length=100)
    date= models.CharField(max_length=100)
    FROM_ID = models.ForeignKey(Login,on_delete=models.CASCADE,default=1,related_name="fuser")
    TO_ID = models.ForeignKey(Login,on_delete=models.CASCADE,default=1,related_name="tuser")

class Diet(models.Model):
    title= models.CharField(max_length=100)
    file= models.CharField(max_length=500)
    TRAINER = models.ForeignKey(Trainer,on_delete=models.CASCADE,default=1)

class Payment(models.Model):
    USER = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    validity_date = models.DateField(default='2023-11-18')
    amount = models.CharField(max_length=100)
    status = models.CharField(max_length=100,default="")
    date = models.DateField(max_length=100,default="")

class Bank(models.Model):
    acholdername = models.CharField(max_length=100)
    card_number = models.CharField(max_length=100)
    cvv = models.CharField(max_length=100)
    expiry_date = models.CharField(max_length=100)
    balance=models.FloatField()


class Rating(models.Model):
    review=models.CharField(max_length=700)
    rating=models.FloatField()
    USER = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    date=models.DateField()
    POSTURE=models.ForeignKey(Posture, on_delete=models.CASCADE, default=1)

users/models.py
import random
import string

from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

# Create your models here.
USER_TYPE_CHOICES={
    ("ADMIN","admin"),
    ("TRAINER","trainer"),
    ("CLIENT","client"),

}
STATUS_CHOICES={
    ("ACTIVE","Active"),
    ("DEACTIVE","Deactive"),
}
from django.core.files.storage import FileSystemStorage
from django.utils import timezone

def generate_unique_filename(instance, filename):
    """
    Function to generate a unique filename based on the current timestamp.
    """
    # Get the file extension
    extension = filename.split('.')[-1]

    # Generate a unique filename
    unique_filename = f"p1_{timezone.now().strftime('%Y%m%d-%H%M%S')}.{extension}"

    return unique_filename
SUBS_CHOICES={("STANDARD","standard"),
              ("PREMIUM","premium"),
              ("ORDINARY","ordinary")}
class Userprofile(AbstractUser):
    #firstname
    phoneno=models.CharField(max_length=20,null=True,blank=True)
    photo=models.ImageField(upload_to=generate_unique_filename,null=True,blank=True)
    email=models.CharField(max_length=100,null=True,blank=True)
    dob=models.CharField(max_length=100,null=True,blank=True)
    gender=models.CharField(max_length=20,null=True,blank=True)
    place=models.CharField(max_length=100,null=True,blank=True)
    subscriptionplan=models.CharField(max_length=100,null=True,blank=True,default='ORDINARY',choices=SUBS_CHOICES)
    otp=models.CharField(max_length=50,null=True,blank=True,default='')
    status = models.CharField(max_length=20,null=True,choices=STATUS_CHOICES,blank=True)
    is_active = models.BooleanField(default=True)
    user_type=models.CharField(max_length=30,null=True,choices=USER_TYPE_CHOICES,blank=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True,blank=True)
    updated_at=models.DateTimeField(auto_now=True,null=True,blank=True)
    def __str__(self):
        return f"{self.pk}-{self.first_name}"
import random
import string
class Token(models.Model):
    key = models.CharField(max_length=50, unique=True)
    user = models.OneToOneField(
        Userprofile,
        related_name="auth_tokens",
        on_delete=models.CASCADE,
        verbose_name="user",
        unique=True,
        null=True,
        blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    session_dict = models.TextField(null=False, default="{}")

    dict_ready = False
    data_dict = None

    def _init_(self, *args, **kwargs):
        self.dict_ready = False
        self.data_dict = None
        super(Token, self)._init_(*args,**kwargs)
    def generate_key(self):
        return "".join(
            random.choice(
                string.ascii_lowercase + string.digits + string.ascii_uppercase
            )
            for i in range(40)
        )
    def save(self, *args, **kwargs):
        if not self.key:
            new_key = self.generate_key()
            while type(self).objects.filter(key=new_key).exists():
                new_key = self.generate_key()
            self.key = new_key
        return super(Token, self).save(*args,**kwargs)

    def read_session(self):
        if self.session_dict == "null":
            self.data_dict = {}
        else:
            self.data_dict = json.loads(self.session_dict)
        self.dict_ready = True
    def update_session(self, tdict, save=True, clear=False):
        if not clear and not self.dict_ready:
            self.read_session()
        if clear:
            self.data_dict = tdict
            self.dict_ready = True
        else:
             for key, value in tdict.items():
                 self.data_dict[key] = value
             if save:
                 self.write_back()

    def set(self, key, value, save=True):
        if not self.dict_ready:
            self.read_session()
        self.data_dict[key] = value
        if save:
            self.write_back()

    def write_back(self):
        self.session_dict = json.dumps(self.data_dict)
        self.save()

    def get(self, key, default=None):
        if not self.dict_ready:
            self.read_session()
        return self.data_dict.get(key, default)

    def _str_(self):
        return str(self.user) if self.user else str(self.id)

users/forms.py
from users.models import (
    Userprofile,
    Token,
)
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from client.models import Clientprofile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = Userprofile
        fields = ("username","phoneno")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = Userprofile
        exclude = []
class Clientregistrationform(forms.ModelForm):
    class Meta:
        model=Clientprofile
        fields=['height','weight']

templates/user/changepwd.html
{% extends 'user/userhome_index.html' %}

{% block body %}

<body>
<div class="container">
    <div class="row">
        <div class="col-lg-12">

<form id="form1" name="form1" method="post" action="/client/user_changepwd_post/">
        {% csrf_token %}

    <table class="table table-bordered">
    <tr>
      <td style="color: white">Old password</td>
      <td>
      <input type="password" name="textfield" id="textfield" class="form-control" required /></td>
    </tr>
    <tr>
      <td style="color: white">New password</td>
      <td>
      <input type="password" name="textfield2" id="textfield2" class="form-control" pattern=".{8,}" title="Eight or more characters" required /></td>
    </tr>
    <tr>
      <td style="color: white">Confirm password</td>
      <td>
      <input type="password" name="textfield3" id="textfield3" class="form-control" pattern=".{8,}" title="Eight or more characters" required/></td>
    </tr>
    <tr>
      <td align="center"colspan="2"><input type="submit" name="button" id="button" value="Submit" class="btn-success" /></td>
    </tr>
  </table>
</form>
   </div>
    </div>
</div>
</body>
{% endblock %}

templates/user/chattemplate2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat History</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        h1 {
            text-align: center;
            margin-top: 20px;
        }

        ul#chat-history {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        li.sent {
            background-color: #DCF8C6;
            border-radius: 10px;
            padding: 10px;
            margin-bottom: 10px;
            text-align: right;
            max-width: 70%;
            margin-left: auto;
            margin-right: 10px;
        }

        li.received {
            background-color: #F0F0F0;
            border-radius: 10px;
            padding: 10px;
            margin-bottom: 10px;
            text-align: left;
            max-width: 70%;
            margin-right: auto;
            margin-left: 10px;
        }

        #chatbox {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-top: 20px;
        }

        input[type="text"] {
            width: calc(100% - 70px);
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
            margin-right: 10px;
        }

        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
    <script>
        $(document).ready(function(){
            // Function to fetch latest chat messages from the server
            function fetchChatHistory(fromId, toId) {
                $.ajax({
                    type: "GET",
                    url: "/trainer/view_chat_history/",  // Specify the URL to fetch chat history
                    data: {
                        sender_id: fromId,
                        recipient_id: toId
                    },
                    success: function(response){
                        // Replace the chat history with the updated messages
                        $("#chat-history").html(response);
                    },
                    error: function(xhr, status, error){
                        // Handle errors if any
                        console.error(xhr.responseText);
                    }
                });
            }

            // Fetch chat history when the page loads
            var senderId = "{{ chat.to_id }}";
            var recipientId = "{{ chat.from_id }}";
            fetchChatHistory(senderId, recipientId);

            // Function to send message using AJAX
            $("#chat-form").submit(function(event){
                event.preventDefault(); // Prevent default form submission
                var formData = $(this).serialize();
                // Serialize form data
                var fromId = $(this).find('input[name="from_id"]').val();
                var toId = $(this).find('input[name="to_id"]').val();
                $.ajax({
                    type: "POST",
                    url: "/trainer/trainerchatpost/",  // Specify the URL to send the message
                    data: formData,

                    success: function(response){
                        // Fetch latest chat messages and update the chat history

                        fetchChatHistory(fromId, toId);
                        form.find('input[name="message"]').val('');

                    },
                    error: function(xhr, status, error){
                        // Handle errors if any
                        console.error(xhr.responseText);
                    }
                });
            });
        });
    </script>
</head>
<body>
    <h1>Chat History</h1>
    <ul id="chat-history">
        <!-- Chat history will be displayed here -->
        {% for chat in chats %}
         <li class="{% if chat.from_id ==  request.session.user_id.0  %}sent{% else %}received{% endif %}">
<!--            <strong>From:</strong> {{ chat.from_id }}<br>-->
<!--            <strong>To:</strong> {{ chat.to_id }}<br>-->
            <strong>Message:</strong> {{ chat.message }}<br>
<!--            <strong>Created At:</strong> {{ chat.created_at }}<br>-->
        </li>
        {% endfor %}
    </ul>
    <div id="chatbox">
        <form id="chat-form" method="post">
            {% csrf_token %}
            {% if to_id %}
            <input type="hidden" name="from_id" value="{{ request.session.user_id.0 }}">
            <input type="hidden" name="to_id" value="{{to_id}}">
            <input type="text" name="message" id="id_message" placeholder="Type your message here" required>
            <button type="submit">Send</button>
            {% endif %}
        </form>
    </div>
</body>
</html>

templates/user/chattemplate3.html
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        h1 {
            text-align: center;
            margin-top: 20px;
        }

        ul#chat-history {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        li.sent {
            background-color: #DCF8C6;
            border-radius: 10px;
            padding: 10px;
            margin-bottom: 10px;
            text-align: right;
            max-width: 70%;
            margin-left: auto;
            margin-right: 10px;
        }

        li.received {
            background-color: #F0F0F0;
            border-radius: 10px;
            padding: 10px;
            margin-bottom: 10px;
            text-align: left;
            max-width: 70%;
            margin-right: auto;
            margin-left: 10px;
        }

        #chatbox {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-top: 20px;
        }

        input[type="text"] {
            width: calc(100% - 70px);
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
            margin-right: 10px;
        }

        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
    <ul id="chat-history">
        <!-- Chat history will be displayed here -->
        {% for chat in chats %}
        <li class="{% if chat.from_id == request.session.user_id.0 %}sent{% else %}received{% endif %}">
<!--            <strong>From:</strong> {{ chat.from_id }}<br>-->
<!--            <strong>To:</strong> {{ chat.to_id }}<br>-->
            <strong>Message:</strong> {{ chat.message }}<br>
<!--            <strong>Created At:</strong> {{ chat.created_at }}<br>-->
        </li>
        {% endfor %}
    </ul>

templates/user/payment.html
{% extends 'user/userhome_index.html' %}

{% block body %}

<body>
<div class="container">
    <div class="row">
        <div class="col-lg-12">

<form id="form1" name="form1" method="post" action="/client/user_payment_post/">
    {% csrf_token %}
    <table class="table table-bordered">
    <tr>
      <td style="color: white">A/c holder name</td>
      <td>
      <input type="text" name="textfield" required="" id="textfield" class="form-control" /></td>
    </tr>
    <tr>
      <td style="color: white">Card number</td>
      <td>
      <input type="text" name="cardno" required="" id="textfield2" class="form-control" /></td>
    </tr>
    <tr>
      <td style="color: white">cvv</td>
      <td>
      <input type="text" name="textfield2" required="" id="textfield2" class="form-control" /></td>
    </tr>
    <tr>
      <td style="color: white">Card validity</td>
      <td>
      <input type="text" name="textfield3" required="" id="textfield3" class="form-control" /></td>
    </tr>
    <tr>
      <td style="color: white">Amount</td>
      <td style="color:red;font-size: 30px;">500</td>
    </tr>
    <tr>
      <td align="center"colspan="2"><input type="submit" name="button" id="button" value="Submit" class="btn btn-success"/></td>
     
    </tr>
  </table>
</form>

        </div>
    </div>
</div>
</body>
{% endblock %}

templates/user/play video.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
</body>
</html>

templates/user/send query chat.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
</body>
</html>

templates/user/sent feedback.html
{% extends 'user/userhome_index.html' %}

{% block body %}

<body>
<div class="container">
    <div class="row">
        <div class="col-lg-12">

<form action="/client/user_sentfeedback_post/" method="post">
    {% csrf_token %}
    <table class="table table-bordered">
  <tr>
    <td  style="color: white" >Feedback</td>
    <td>
      <textarea name="textarea" id="textarea" cols="45" rows="5" required class="form-control"></textarea></td>
  </tr>
  <tr>
    <td align="center"colspan="2"><input type="submit" name="button" id="button" value="send" class="btn btn-success" /></td>
  </tr>
</table>
</form>

        </div>
    </div>
</div>
</body>
{% endblock %}

templates/user/userhomepage.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body><form action="" method="get">

<a href="/myapp/user_viewprofile/">View profile</a><br/>
<a href="/myapp/user_view_trainer/">View Trainer</a><br/>
<a href="/myapp/user_viewposture/">View posture</a><br/>
<a href="/myapp/user_payment/">Add payment</a><br/>
<a href="/myapp/user_viewdietplan/">View diet plan</a><br/>
    <a href="/myapp/user_sentcomplaint/">Sent complaint</a><br/>
<a href="/myapp/user_viewcomplaintreply/">View complaint</a><br/>
<a href="/myapp/user_sentfeedback/">sent feedback</a><br/>
<a href="/myapp/user_sendquery/">Raise query</a><br/>
<a href="/myapp/user_changepwd/">Change password</a><br/>
<a href="/myapp/user_logout/">Logout</a><br/>









</form>
</body>
</html>

templates/user/view diet plan.html
{% extends 'user/userhome_index.html' %}

{% block body %}


<body>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
<form action="/client/user_viewdietplan_post/#hii" method="post">
    {% csrf_token %}
<table  class="px pull-left">
  <tr>
    <td>
      <input type="text" name="textfield" id="textfield" placeholder="Title"/></td>
    <td><input type="submit" name="button" id="button" value="Search" class="btn btn-success" /></td>
    
  </tr>
</table>
<br>
<br>
<br>
    <table class="table table-bordered">
    <tr>
        <td style="color: white">sl.no</td>
      <td style="color: white">Title</td>
    <td style="color: white">Trainer</td>
        <td style="color: white">file</td>
    </tr>
      {%  for i in data  %}
    <tr>
      <td style="color: white">{{ forloop.counter}}</td>
      <td style="color: white">{{ i.title }}</td>
      <td style="color: white">{{ i.trainer.first_name }}</td>
      <td style="color: white"><a href="{{ i.file.url }}" target="_blank" class="btn btn-info">download</a> </td>
    </tr>
      {% endfor %}
  </table>
</form>

        </div>
    </div>
</div>
</body>
{% endblock %}